// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TabController from "./tab_controller"
application.register("tab", TabController)

import SearchClearController from "./search_clear_controller"
application.register("search-clear", SearchClearController)

import StatusBarController from "./status_bar_controller"
application.register("status-bar", StatusBarController)